### ISSUE TITLE
Compatibility issue with AutomatedAnimations

### ISSUE THREAD

**Issue by doctorthoss** [Xacus/demonlord#117]
There's currently an issue with triggering animations from the very popular Automated Animations module when it is set to play animations on attack rolls and not damage rolls. Details are in the link below, the dev there is working on it but indicated he needed help from someone with insider knowledge of the SotDL system

https://github.com/otigon/automated-jb2a-animations/issues/541

**Comment by doctorthoss** [comment]
the root cause of this is possibly: https://github.com/Xacus/demonlord/issues/118

**Comment by juanferrer** [comment]
Can you re-test with v2.2.5? If it was related, it should be fixed now.

**Comment by doctorthoss** [comment]
> Can you re-test with v2.2.5? If it was related, it should be fixed now.

Thanks again for your work on this! So it isn't 100% fixed, but it is partially fixed and the behavior has changed, so it's definitely related to the die rolls somehow. To sum up, here is how Automated Animations behaves:

**Before your patch**
When set to play animations on attack roll, weapons would work as expected. Talents and Spells would play animations only if there was no associated damage roll. For Talents and Spells with an associated damage roll, the only way to get them to play an animation at all is to change Automated Animations to "play animations on roll damage." This results in some awkwardness like animations never being played if a player misses (because then we don't roll damage), etc.

**After your patch**
Weapons still work as they should, and Talents now work as well! Meaning that talents with associated damage rolls _do_ play an animation on the attack roll, with Automated Animations set to "play animation on attack roll." Spells, however, still behave the same way as they did before described above. So somehow the patch fixed the issue with Talents but not with Spells

**Comment by juanferrer** [comment]
Fixed by [PR #672](https://github.com/otigon/automated-jb2a-animations/pull/672) in Automated Animations repo.
